# -*- coding: utf-8 -*-
"""Lab5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19qOOKXEnRjkHc2SuGKBBbDGp6cmEAEhl

Muhammad Mohsin Ali 
FA20-BSE-072
"""

def isPalindrome(word):
  temp=word[::-1]
  if temp.capitalize()== word.capitalize():
    return True
  else:
    return False 
print(isPalindrome("deed"))

word=input(" enter a word  ")
def isPalindrome(word):
  temp=word[::-1]
  print(temp.upper())
  if temp.capitalize()== word.capitalize():
    return True
  else:
    return False 
print(isPalindrome(word))

a=[[1,0,0],[0,1,0],[0,0,1]]
b=[[1,2,3],[4,5,6],[7,8,9]]
print(a[-3])

a=[[1,0,0],[0,1,0],[0,0,1]]
b=[[1,2,3],[4,5,6],[7,8,9]]
print(a[2][2])

a=[[[1,0,0],[0,1,0],[0,0,1]],[[1,2,3],[4,5,6],[7,8,9]]]
print(a[-1][0][-1])